In [104]:
# 패키지 임포트
import numpy as np
import pandas as pd
import scipy.stats as ss
import os 
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import minmax_scale
from sklearn.preprocessing import LabelEncoder
from datetime import datetime
# !pip install plotly
# import plotly.offline as off
# import plotly.graph_objs as go
pd.set_option('display.max_columns', 500)

plt.rc("font", family="Malgun Gothic") # matplotlib 한글깨짐 방지

In [114]:
hospital_data = pd.read_csv('병원.csv')

In [115]:
hospital_data.drop('동', axis=1, inplace=True)

In [116]:
hospital_data

     자치구  대학병원 병원수  대학병원 병상수  종합 병원수  종합 병상수
0    종로구         0         0       0       0
1    종로구         0         0       1      30
2    종로구         0         0       0       0
3    종로구         0         0       1     123
4    종로구         1       218       0       0
..   ...       ...       ...     ...     ...
419  강동구         0         0       0       0
420  강동구         1       965       0       0
421  강동구         0         0       0       0
422  강동구         0         0       1      32
423  강동구         1       620       3     237

[424 rows x 5 columns]

# 1. 구 별 집계

In [117]:
group_by_gu = hospital_data.groupby('자치구').sum()
group_by_gu = group_by_gu.reset_index()
group_by_gu

     자치구  대학병원 병원수  대학병원 병상수  종합 병원수  종합 병상수
0    강남구         4      3115      33    2067
1    강동구         3      2250      14     913
2    강북구         1       203       8     802
3    강서구         3       459      16    1366
4    관악구         2       479       8     515
5    광진구         2      1087       3     179
6    구로구         2      1261       8     608
7    금천구         1       236       6     704
8    노원구         3      1664       7     471
9    도봉구         1       414       5     525
10  동대문구         5      2035      14    1608
11   동작구         2      1599       5     401
12   마포구         0         0       2     187
13  서대문구         2      2667       4     178
14   서초구         1      1356      10     955
15   성동구         1       844       7     634
16   성북구         1      1051       6     471
17   송파구         2      3175      16    1334
18   양천구         2      1064       5     750
19  영등포구         7      2129       9     998
20   용산구         1       727       2     174
21   은평구         1       200       9     655
22   종로구         4      2978       2     153
23    중구         3      1035       3     261
24   중랑구         3      1049      12     831

In [118]:
# 병상수 드랍
group_by_gu.drop('대학병원 병상수', axis=1, inplace=True)
group_by_gu.drop('종합 병상수', axis=1, inplace=True)

In [120]:
group_by_gu.to_csv('hospital.csv')